= Visitor Use Management Tool

image::https://travis-ci.org/aepstein/vumt.svg?branch=master[]

== About

This is a prototypal tool intended to illustrate how the visitor registration process for many preserves in New York State, such as the public forest preserve lands in the Adirondack Park, could be conducted online.
Currently, most preserves in New York feature paper-based registers at popular access points where visitors are expected to sign in and provide a limited amount of information.
This tool seeks to provide an online alternative where visitors can register online using mobile devices.

This is an experimental application provided without warranty.
Use at your own risk.

== Structure of Project

Key folders:

* client: Contains client application assets. Client is a React javascript application that speaks to the server API.
* features: End-to-end tests.
* routes: Controller and route definitions for the server, which is mainly an expressJS backend that serves a REST-ful JSON API.
* test: Unit tests.

== Contribution Guidelines

Contributions are welcome.
Please see the issues page for this project and contact the project maintainer for guidance on where to focus.
Accepted contributions will be incorporated into the project and licensed under the same terms by which this project is made available.
Do not contribute code or other intellectual property unless you have ownership or license to release it under the terms of this project's license.

Contributions must be robust, well-formed, and accompanied by a comprehensive suite of unit and end-to-end tests.

== Acknowledgments

The initial design of this project was made possible in part by tutorials provided by link:https://www.traversymedia.com/[Traversy Media].
The terms of service and privacy policy for our project were adapted from the policies of the open source link:https://www.kobotoolbox.org/[KoBoToolbox] project.

== Copyright

Copyright 2019, 2020 Adirondack Wilderness Advocates, Inc.
See LICENSE file for terms of use.