const errorCodes = {
    E_AUTH_EXPIRED_PASSWORD_RESET_TOKEN: 'AUTH_EXPIRED_PASSWORD_RESET_TOKEN',
    E_AUTH_EXPENDED_PASSWORD_RESET_TOKEN: 'AUTH_EXPENDED_PASSWORD_RESET_TOKEN',
    E_AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
    E_AUTH_INVALID_USER_TOKEN: 'AUTH_INVALID_USER_TOKEN',
    E_AUTH_MISSING_EMAIL: 'AUTH_MISSING_EMAIL',
    E_AUTH_MISSING_PASSWORD: 'AUTH_MISSING_PASSWORD',
    E_AUTH_NEED_ROLE: 'AUTH_NEED_ROLE',
    E_AUTH_NO_USER_TOKEN: 'AUTH_NO_USER_TOKEN',
    E_AUTH_NO_PASSWORD_RESET_TOKEN: 'AUTH_NO_PASSWORD_RESET_TOKEN',
    E_AUTH_NO_USER: 'AUTH_NO_USER',
    E_AUTH_REQUIRED: 'AUTH_REQUIRED',
    E_USER_UNAUTHORIZED: 'USER_UNAUTHORIZED'
}

module.exports = errorCodes